require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'CATMobile' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNCPicker', :path => '../node_modules/@react-native-picker/picker'


  pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation-locker'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  target 'CATMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'CATMobile-tvOS' do
  # Pods for CATMobile-tvOS

  target 'CATMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
